import streamlit as st
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from algorithm import (
    kruskal,
    prim,
    build_adj
)


def app():

    st.header("🌳 Minimum Spanning Tree")
    st.subheader("Prim's Algorithm vs Kruskal's Algorithm")

    st.markdown("""
This dashboard compares the Minimum Spanning Tree generated by

- Prim's Algorithm
- Kruskal's Algorithm
""")

    # -------------------------------------------------
    # Sidebar
    # -------------------------------------------------

    st.sidebar.header("Graph Input")

    default_edges = """7 0 1
5 0 3
8 1 2
9 1 3
7 1 4
5 2 4
15 3 4
6 3 5
8 4 5
9 4 6
11 5 6"""

    vertices = st.sidebar.number_input(
        "Number of Vertices",
        min_value=2,
        value=7,
        key="mst_vertices"
    )

    edge_text = st.sidebar.text_area(
        "Edges (weight source destination)",
        value=default_edges,
        height=250,
        key="mst_edges"
    )

    run = st.sidebar.button(
        "Generate MST",
        key="run_mst"
    )

    # -------------------------------------------------
    # Parse Input
    # -------------------------------------------------

    edges = []

    try:

        for line in edge_text.strip().split("\n"):

            if line.strip():

                w, u, v = map(int, line.split())

                edges.append((w, u, v))

    except:

        st.error(
            "Invalid edge format.\nUse:\nweight source destination"
        )
        return

    if not run:
        return

    # -------------------------------------------------
    # Execute Algorithms
    # -------------------------------------------------

    adj = build_adj(edges)

    kruskal_mst, kruskal_cost = kruskal(
        vertices,
        edges.copy()
    )

    prim_mst, prim_cost = prim(
        vertices,
        adj
    )

    # -------------------------------------------------
    # Metrics
    # -------------------------------------------------

    st.subheader("MST Cost")

    col1, col2 = st.columns(2)

    with col1:

        st.metric(
            "Kruskal Cost",
            kruskal_cost
        )

    with col2:

        st.metric(
            "Prim Cost",
            prim_cost
        )

    # -------------------------------------------------
    # MST Tables
    # -------------------------------------------------

    st.subheader("Minimum Spanning Tree Edges")

    left, right = st.columns(2)

    with left:

        st.markdown("### Kruskal")

        df1 = pd.DataFrame(
            kruskal_mst,
            columns=[
                "Source",
                "Destination",
                "Weight"
            ]
        )

        st.dataframe(
            df1,
            use_container_width=True
        )

    with right:

        st.markdown("### Prim")

        df2 = pd.DataFrame(
            prim_mst,
            columns=[
                "Source",
                "Destination",
                "Weight"
            ]
        )

        st.dataframe(
            df2,
            use_container_width=True
        )

    # -------------------------------------------------
    # Comparison Table
    # -------------------------------------------------

    st.subheader("Comparison")

    compare = pd.DataFrame({

        "Algorithm": [
            "Kruskal",
            "Prim"
        ],

        "Total Cost": [
            kruskal_cost,
            prim_cost
        ],

        "Edges": [
            len(kruskal_mst),
            len(prim_mst)
        ]

    })

    st.dataframe(
        compare,
        use_container_width=True
    )

    # -------------------------------------------------
    # Original Graph
    # -------------------------------------------------

    st.subheader("Original Graph")

    G = nx.Graph()

    for w, u, v in edges:

        G.add_edge(
            u,
            v,
            weight=w
        )

    pos = nx.spring_layout(
        G,
        seed=42
    )

    fig, ax = plt.subplots(
        figsize=(8, 6)
    )

    nx.draw_networkx_nodes(
        G,
        pos,
        node_size=700,
        ax=ax
    )

    nx.draw_networkx_labels(
        G,
        pos,
        ax=ax
    )

    nx.draw_networkx_edges(
        G,
        pos,
        width=2,
        edge_color="lightgray",
        ax=ax
    )

    nx.draw_networkx_edge_labels(
        G,
        pos,
        edge_labels=nx.get_edge_attributes(G, "weight"),
        ax=ax
    )

    st.pyplot(fig)

    # -------------------------------------------------
    # Kruskal Visualization
    # -------------------------------------------------

    st.subheader("Kruskal MST")

    fig2, ax2 = plt.subplots(
        figsize=(8, 6)
    )

    nx.draw_networkx_nodes(
        G,
        pos,
        node_size=700,
        ax=ax2
    )

    nx.draw_networkx_labels(
        G,
        pos,
        ax=ax2
    )

    nx.draw_networkx_edges(
        G,
        pos,
        edge_color="lightgray",
        width=2,
        ax=ax2
    )

    mst_edges = [

        (u, v)

        for u, v, w in kruskal_mst

    ]

    nx.draw_networkx_edges(
        G,
        pos,
        edgelist=mst_edges,
        edge_color="red",
        width=4,
        ax=ax2
    )

    nx.draw_networkx_edge_labels(
        G,
        pos,
        edge_labels=nx.get_edge_attributes(G, "weight"),
        ax=ax2
    )

    st.pyplot(fig2)

    # -------------------------------------------------
    # Prim Visualization
    # -------------------------------------------------

    st.subheader("Prim MST")

    fig3, ax3 = plt.subplots(
        figsize=(8, 6)
    )

    nx.draw_networkx_nodes(
        G,
        pos,
        node_size=700,
        ax=ax3
    )

    nx.draw_networkx_labels(
        G,
        pos,
        ax=ax3
    )

    nx.draw_networkx_edges(
        G,
        pos,
        edge_color="lightgray",
        width=2,
        ax=ax3
    )

    prim_edges = [

        (u, v)

        for u, v, w in prim_mst

    ]

    nx.draw_networkx_edges(
        G,
        pos,
        edgelist=prim_edges,
        edge_color="green",
        width=4,
        ax=ax3
    )

    nx.draw_networkx_edge_labels(
        G,
        pos,
        edge_labels=nx.get_edge_attributes(G, "weight"),
        ax=ax3
    )

    st.pyplot(fig3)

    # -------------------------------------------------
    # Result
    # -------------------------------------------------

    if kruskal_cost == prim_cost:

        st.success(
            "✅ Both algorithms generated the same MST cost."
        )

    else:

        st.error(
            "❌ The generated MST costs are different."
        )